theme = "hyde"
baseURL = "https://samuelcrane.netlify.com/"
languageCode = "en-us"
title = "Samuel Crane"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  themeColor = "theme-prussian"
  description = "Hello. I am a data scientist & tech manager in New York City."
  copyright = " "