theme = "hyde"
baseURL = "https://youthful-blackwell-29b276.netlify.com/"
languageCode = "en-us"
title = "Samuel Crane"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  themeColor = "theme-base-0g"
  description = "Hello. I am a data scientist and tech manager in New York City."
  copyright = " "